- src/strands/models/bedrock.py
This change adds "strands-agents" to the user agent for API calls to Bedrock. The user-agent shows up in CloudTrail logs, enabling users to understand where Bedrock calls are coming from.
> fix: set user-agent for Bedrock API calls

- README.md
Typo in the examples tools header referencing the wrong repo
> Update README.md mention of tools repo

- src/strands/telemetry/tracer.py
- tests/strands/telemetry/test_tracer.py
Fixes traces when non-serializable data (like bytes from images, videos, audio, etc.) are present.
Before fixes (output incorrectly shows `<replaced>`): https://us.cloud.langfuse.com/project/cmaoqkqd901afad07ui6ndt1v/traces/36829363ba6e9f5177322c5edaf3b0fc?timestamp=2025-05-17T17:03:02.274Z&display=details
After fixes (only the image_reader tool output bytes show `<replaced>`, which is correct): https://us.cloud.langfuse.com/project/cmaoqkqd901afad07ui6ndt1v/traces/0ee3d42598ab472721c884a23caf36fa?timestamp=2025-05-17T21%3A17%3A17.318Z&display=details
- Bug fix
* `hatch run test-integ`
* Verify that the changes do not break functionality or introduce warnings in consuming repositories: agents-docs, agents-tools, …
> fix: tracing of non-serializable values, e.g. bytes

- src/strands/models/bedrock.py
- tests/strands/models/test_bedrock.py
Use the `AWS_REGION` environment variable for the Bedrock model provider region if set and boto_session is not passed.
https://github.com/strands-agents/sdk-python/issues/38
https://github.com/strands-agents/docs/pull/15
- Bug fix
* `hatch run test-integ`
* Manually tested by:
1. Setting `AWS_REGION` to `us-west-1`, got an error as expected because Bedrock is not available in us-west-1: `botocore.errorfactory.ValidationException: An error occurred (ValidationException) when calling the ConverseStream operation: Your account is not authorized to invoke this API operation.`
2. Unset `AWS_REGION`, fell back to `us-west-2` and succeeded as expected
By submitting this pull request, I confirm that you can use, modify, copy, …
> fix(bedrock): use the AWS_REGION environment variable for the Bedrock model provider region if set and boto_session is not passed

- src/strands/agent/agent.py
- tests/strands/agent/test_agent.py
This PR updates references to direct tool calls to use the new format `agent.tool.tool_name` instead of the old `agent.tool_name`.
Fixes: https://github.com/strands-agents/sdk-python/issues/42.
> fix: update direct tool call references

- CONTRIBUTING.md
- STYLE_GUIDE.md
- pyproject.toml
- src/strands/telemetry/tracer.py
Adding style guide to cover preferences we do not yet have codified into our automatic linters.
> style guide

- CONTRIBUTING.md
- src/strands/agent/conversation_manager/conversation_manager.py
- src/strands/event_loop/error_handler.py
- src/strands/models/bedrock.py
- src/strands/types/guardrails.py
- src/strands/types/media.py
Fixing various typos in markdowns and scripts. See commit diffs for details.
Fixing some typos in code comments and markdowns
> fixing various typos in markdowns and scripts

- src/strands/models/bedrock.py
Previously if the caller provided a botocore Config, we did not set the user agent to strands-agents. However, it turns out it's fairly common to provide a Config to set retries.  This change adds to the caller's user agent if present, and otherwise sets it to user agent.  The botocore Config merge method ensures that we don't lose any of the caller's Config settings.
> fix: Merge strands-agents user agent into existing botocore config

- CONTRIBUTING.md
- pyproject.toml
- src/strands/handlers/tool_handler.py
Since the project is already using `hatch` as the build backend, it would be a more consistent development experience to also manage the python virtual environments using `hatch shell`.
I added a new env named `dev` so that contributor can use `hatch shell dev` to enter this virtual environment. It includes every optional features.
- Other (please describe): contributing guide
yes
> docs: update contributing guide to manage python env with hatch shell

- src/strands/telemetry/tracer.py
- tests/strands/telemetry/test_tracer.py
This PR adds ensure_ascii=False parameter to all json.dumps() calls in the telemetry tracer module. This change ensures proper handling of non-ASCII characters (such as Japanese, Chinese, or emoji) in telemetry data by preventing them from being escaped as \uXXXX sequences in JSON output. The modification improves readability of logs and telemetry data when working with international content.
No specific issue ticket, addressing as part of internationalization improvements.
N/A - This is an internal implementation change that doesn't require documentation updates.
- Bug fix
• [x] hatch fmt --linter
• [x] hatch fmt --formatter
• [x] hatch test --all
- [-] I have updated the documentation accordingly
- [-] I have added an appropriate example to the documentation to outline the feature
By …
> Add ensure_ascii=False to json.dumps() calls in telemetry tracer

- pyproject.toml
This fixes https://github.com/strands-agents/sdk-python/issues/88
Because we used the latest open-telemetry version if someone has a lower version required (as in the issue above) then it makes it difficult to install the SDK 
Looking at the release notes for the library at https://github.com/open-telemetry/opentelemetry-python/releases this seems like a safe change.
https://github.com/strands-agents/sdk-python/issues/88
Bug fix
> Lower OpenTelemetry minimum version

- .gitignore
- src/strands/handlers/callback_handler.py
- tests/strands/handlers/test_callback_handler.py
**Handler Implementation (callback_handler.py):**
- The `PrintingCallbackHandler` now checks for the `reasoningText` argument and prints it if present.
- The handler’s logic for printing `data`, handling completion, and tracking tool usage remains consistent with the updated tests.
- No breaking changes to the handler logic; changes ensure the implementation matches the new and clarified test expectations.
**Unit Test Improvements for Callback Handler (test_callback_handler.py):**
- Added and clarified tests for the `reasoningText` argument in the `PrintingCallbackHandler`.
- Explicitly test the handler’s behavior when `reasoningText` is present (should print the text) and when it is absent (should not print reasoning text).
- Ensured that combinations of `reasoningText` and `data` are …
> feat(handlers): add reasoning text to callback handler and related tests

- src/strands/event_loop/event_loop.py
🔨 Modularizing Event Loop Logic
Commit: 8cb8422
Author: Fede Kamelhar
Date: May 25, 2025
Message: Modularizing Event Loop
⸻
✨ What’s Included
1. Extracted Tool Execution Logic
Moved all logic related to handling tool_use into a dedicated private function: _handle_tool_execution().
Benefit:
Improves readability, simplifies event_loop_cycle(), and separates concerns for better maintainability and testing.
New function:
```python
def _handle_tool_execution(...) -> Tuple[StopReason, Message, EventLoopMetrics, Dict[str, Any]]:
```
```python
if stop_reason == "tool_use":
return _handle_tool_execution(...)
```
2. Centralized Retry Configuration
Introduced constants for retry settings, replacing hardcoded values:
```python
MAX_ATTEMPTS = 6
INITIAL_DELAY = 4
MAX_DELAY = 240  # 4 minutes
``` …
> # 🔥🕊️ Rise of the Phoenix: Event Loop Refactor

- src/strands/agent/agent.py
- tests/strands/agent/test_agent.py
Fix agent span start and end when using Agent.stream_async()
https://github.com/strands-agents/sdk-python/issues/118
N/A
- Bug fix
* `hatch fmt`
* `hatch run test-lint`
* `hatch run test-integ`
* Verified manually with a test script (trace: https://us.cloud.langfuse.com/project/cmaoqkqd901afad07ui6ndt1v/traces/274b27477f1192d0134307ddd3539743?timestamp=2025-05-26T16%3A31%3A17.773Z&display=details):
```python
#!/usr/bin/env python
import asyncio
import logging
import os
from strands import Agent, tool
from strands_tools import calculator, http_request, image_reader
logging.getLogger("strands.telemetry.tracer").setLevel(logging.DEBUG)
logging.basicConfig(
format="%(levelname)s | %(name)s | %(message)s",
handlers=[logging.StreamHandler()]
) …
```
> fix(telemetry): fix agent span start and end when using Agent.stream_async()

- src/strands/handlers/callback_handler.py
fix docstring for PrintingCallbackHandler.__call__
resolves:
```
WARNING -  griffe: /Users/arron/.env/lib/python3.13/site-packages/strands/handlers/callback_handler.py:20: Parameter '-' does not appear in the function signature
WARNING -  griffe: /Users/arron/.env/lib/python3.13/site-packages/strands/handlers/callback_handler.py:21: Parameter '-' does not appear in the function signature
WARNING -  griffe: /Users/arron/.env/lib/python3.13/site-packages/strands/handlers/callback_handler.py:22: Parameter '-' does not appear in the function signature
WARNING -  griffe: /Users/arron/.env/lib/python3.13/site-packages/strands/handlers/callback_handler.py:23: Parameter '-' does not appear in the function signature
```
* `hatch fmt`
* `hatch run test-lint`
* `hatch test …
> style(callback_handler): fix docstring for PrintingCallbackHandler.__call__

- tests/strands/event_loop/test_message_processor.py
🧪 Test Suite Overview for message_processor
This test module provides coverage for key utility functions in message_processor.py under strands.event_loop, specifically validating behavior related to message sanitization and correction in tool use scenarios. The tests are structured with pytest and include parameterized inputs for robustness.
✅ test_clean_orphaned_empty_tool_uses
Tests the function clean_orphaned_empty_tool_uses, which removes or replaces toolUse messages that:
•	Have empty input
•	Do not have a matching toolResult
This ensures the message history doesn’t contain stale or incomplete tool use entries. The test checks both whether the cleanup happened and what the cleaned messages look like.
🔍 test_find_last_message_with_tool_results
Validates …
> Increasing Coverage Message Processor : From 79% to 94%

- README.md
- src/strands/models/bedrock.py
- src/strands/types/streaming.py
- tests-integ/test_model_bedrock.py
- tests/strands/models/test_bedrock.py
Add support for non-streaming bedrock models
https://github.com/strands-agents/sdk-python/issues/32
https://github.com/strands-agents/docs/pull/65
- Bug fix
- New feature
- Breaking change
- Other (please describe):
New feature
> feat: Add non-streaming support to BedrockModel

- src/strands/telemetry/tracer.py
- tests/strands/telemetry/test_tracer.py
[Provide a detailed description of the changes in this PR]
Correct environment variable precedence for OTEL config
[Link to related issues using #issue-number format]
[Link to related associated PR in the agent-docs repo]
x Bug fix
- New feature
- Breaking change
- Other (please describe):
[Choose one of the above types of changes]
Local test and local deploy, test otel behavior then validate via Langfuse.
- [x ] I have read the CONTRIBUTING document
- [x ] I have added tests that prove my fix is effective or my feature works …
> fix(telemetry): correct environment variable precedence for OTEL config

- src/strands/agent/agent.py
- src/strands/agent/conversation_manager/conversation_manager.py
- src/strands/agent/conversation_manager/null_conversation_manager.py
- src/strands/agent/conversation_manager/sliding_window_conversation_manager.py
- tests/strands/agent/test_agent.py
- tests/strands/agent/test_conversation_manager.py
Refactor the ConversationManager so that it can take in an `Agent` instead of a list of messages. This is to simplify the interface, and better support the new SummarizationConversationManager implementation: https://github.com/strands-agents/sdk-python/pull/112
https://github.com/strands-agents/sdk-python/issues/90
No changes needed
- Bug fix
- New feature
- Breaking change
- Other (please describe):
> refactor: Update conversation manager interface

- tests/conftest.py
- tests/strands/tools/test_executor.py
Fixes scenario where tests fail when `OTEL_` environment variables are set in the environment where tests are ran.
N/A
N/A
- Bug fix
- Tests fix
* `hatch fmt`
* `hatch run test-lint`
* `hatch test`
* `hatch run test-integ`
> test: set OTEL_ env vars correctly for tests

- src/strands/tools/tools.py
- tests/strands/tools/test_tools.py
- Modifying normalisation logic to recursively processes nested objects to preserve the complete schema structure
- Adding tests for schema's with nested objects
#124 
- Bug fix
* Tested with own `strands-agents` implementation
> Fix: Preserve deeply nested schemas

- .github/workflows/pypi-publish-on-release.yml
Add permission block to call-tst-lint job
N/A
N/A
- Bug fix
- New feature
- Breaking change
- Other (please describe):
Bug fix
> Add permission block to call-tst-lint job

- src/strands/agent/__init__.py
- src/strands/agent/conversation_manager/__init__.py
- src/strands/agent/conversation_manager/summarizing_conversation_manager.py
- tests-integ/test_summarizing_conversation_manager_integration.py
- tests/strands/agent/test_summarizing_conversation_manager.py
> [!TIP]
> Follows conventional commits. Better reviewed commit-by-commit.
Introducing a new `SummarizingConversationManager` as an alternative to the existing sliding window approach. It optionally uses AI-powered summarization to retain the semantic context of older messages, rather than discarding them, while staying within model context limits.
Closes https://github.com/strands-agents/sdk-python/issues/90
https://github.com/strands-agents/docs/pull/63
- New feature
> feat: implement summarizing conversation manager

- src/strands/agent/agent.py
- src/strands/telemetry/tracer.py
- src/strands/tools/registry.py
- tests/strands/agent/test_agent.py
- tests/strands/tools/test_registry.py
Follow-up to #178, where we discussed preventing `similar_tool` and `similar-tool` from both being added to the tool registry, to avoid ambiguity in direct-method invocations.
This removes the need for direct-method invocations from checking for similar names, thus that code was removed
#178, #139
N/A
- Other (please describe): Refactor
> refactor: Disallow similar tool names in the tool registry

- .github/workflows/integration-test.yml
- src/strands/agent/agent.py
- src/strands/telemetry/tracer.py
- tests-integ/conftest.py
- tests-integ/test_bedrock_guardrails.py
- tests-integ/test_mcp_client.py
- tests-integ/test_model_litellm.py
This PR implements secure integration testing via GitHub Actions. It adds a workflow that safely executes integration tests against LLMs while maintaining security through proper authentication and access controls.
Regarding security concerns and their mitigations, we have implemented several layers of protection. For external contributor access, workflows require explicit approval and PRs from forks do not automatically receive access to secrets or OIDC. Credential protection is achieved through short-lived credentials using GitHub Actions OIDC, with secrets managed through secure mechanisms and access strictly limited to specific resources and actions.
Code execution is controlled through the use of pull_request_target for trusted execution context, requiring either owner status or an …
> ci: add integration test workflow

- pyproject.toml
- src/strands/telemetry/tracer.py
- tests-integ/test_mcp_client.py
- tests/strands/telemetry/test_tracer.py
This PR separates out the OTEL http exporter dependency into a separate target and adds A2A SDK dependency.
**NOTE**: any customer integrating Strands with A2A will not be able to use OTEL http exporting.
- https://github.com/google-a2a/a2a-python/issues/198
- Issue to a2a-python repo: https://github.com/google-a2a/a2a-python/issues/198
- Planned for a separate PR. Tracking issue: https://github.com/strands-agents/private-sdk-python-staging/issues/76
- Bug fix
* hatch test
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, …
> build(a2a): add a2a deps and mitigate otel conflict

- src/strands/telemetry/tracer.py
- tests/strands/telemetry/test_tracer.py
This is a followup to #232. After speaking with @zastrowm we agreed that it is better to explicitly raise an exception if a customer relies on Strand's internally configured OTEL HTTP exporter. The goal is to avoid a situation where a customer has deployed a Strands agent to production and after #232 their telemetry is no longer being exported. The overall blast radius of this change is minimal as outlined in #232.
Planned for a separate PR. Tracking issue: https://github.com/strands-agents/private-sdk-python-staging/issues/76
- Followup
By submitting this pull request, I confirm …
> chore(otel): raise exception if exporter unavailable

- .github/workflows/integration-test.yml
This pull request adds a secure check to ensure that the integration tests require approval if the PR creator does not have write access. If the creator has write access or higher, then it will run without approval.
Based on discussion with @Unshure 
N/A
N/A
- Bug fix
Tested in my fork to confirm the permission check works: https://github.com/AdnaneKhan/sdk-python/actions/runs/15708340706/job/44259494661
> fix: Update PR Integration Test Workflow

- src/strands/agent/agent.py
- src/strands/telemetry/__init__.py
- src/strands/telemetry/config.py
- src/strands/telemetry/metrics.py
- src/strands/telemetry/metrics_constants.py
- src/strands/telemetry/tracer.py
- tests/strands/telemetry/test_metrics.py
- tests/strands/telemetry/test_tracer.py
Initiated OTEL Meter in Strands in order to send metrics.
Note:
User has to setup global meter_provider for strands to use them directly (will update the documentation).
Will update the documentation along with the traces.
- New feature
- Added unit tests
- Tested manually with and without global OTEL Meter setup:
```
resource = Resource.create({ResourceAttributes.SERVICE_NAME: "strands-otel-test", "environment": "test"})
console_metric_reader = PeriodicExportingMetricReader(ConsoleMetricExporter())
metrics_provider = MeterProvider(resource=resource, metric_readers=[console_metric_reader])
metrics.set_meter_provider(metrics_provider)
```
* Verify that the changes do not break functionality or introduce warnings in …
> feat: add meter

- src/strands/event_loop/event_loop.py
- tests/strands/event_loop/test_event_loop.py
While reading the through the event loop (in an unrelated POC), it made more sense to me to inline the initialization of state as most of the code was signature + docs, while the actual code is 2 lines each.
N/A
N/A
Other (please describe): Small refactor
> chore: Inline event loop helper functions

- src/strands/models/bedrock.py
- tests/strands/models/test_bedrock.py
We've received customer confusion regarding some of the errors when attempting to run on bedrock. To help customers understand what's going wrong, add region and model information to exceptions coming out of the bedrock provider & point them to our docs when possible.
Semi-related to #238
**Note**:  Python's [`add_note` method](https://docs.python.org/3/library/exceptions.html#BaseException.add_note) was added in 3.11 even though we support 3.10 so this is conditional on being on python 3.11+.  I figured that's okay since this is an *extra* feature of strands.
#238
strands-agents/docs/pull/102
New feature
When you don't …
> Add additional exception information for common bedrock errors

- src/strands/telemetry/tracer.py
The docstring of get_tracer() in tracer.py mentions a fifth argument that does not exist. This PR removes the incorrect line describing this "trace_provider": see commit diff.
N/A
The above can also be considered as a doc chamge
----
> fix: correcting incorrect docstring in tracer.py - non-existing argument documented

- src/strands/agent/agent.py
- src/strands/agent/conversation_manager/null_conversation_manager.py
- src/strands/models/anthropic.py
- src/strands/models/bedrock.py
- src/strands/models/litellm.py
- src/strands/models/llamaapi.py
- src/strands/models/ollama.py
- src/strands/models/openai.py
- src/strands/tools/decorator.py
- src/strands/types/models/model.py
- src/strands/types/models/openai.py
Docs were throwing warnings due to several docstring issues. This pr fixes those
N/A
N/A
Warning fix
----
> fix: Fix docs warnings

- src/strands/models/bedrock.py
- tests/strands/models/test_bedrock.py
Only use a default region if the session doesn't provide one or if the AWS_REGION environment variable is not set. Previously we were using us-west-2 even if the session could load it from the environment (either variables or profiles).  No we only specify a region if the session doesn't provide one
Fixes #238 
#238 
N/A
Bug fix
I tested creating an agent:
- With a profile region set (boto3 default behavior)
- With an environment variable AWS_REGION specified (our custom behavior)
-  With an environment variable AWS_DEFAULT_REGION specified (boto3 default behavior)
-  Explicitly passing a region
- Using the default …
> Use region from boto3 session when possible

- src/strands/telemetry/tracer.py
- tests/strands/telemetry/test_tracer.py
1. Update the SpanKind following the conventions.
- Mark `model_invoke` span and `start_agent` span with SpanKind: CLIENT
- Mark `event_loop`, `tool_call`, default to SpanKind.INTERNAL
2. Add first simple semantic conventions on metrics related data
- This will unblock genesis team about the mappings.
Will update trace attributes after all semantic conventions are merged.
- trace span small update
- [] I have updated the documentation accordingly
----
> chore: update spanKind and attributes for tokens

- src/strands/agent/agent.py
- src/strands/event_loop/event_loop.py
- src/strands/handlers/tool_handler.py
- src/strands/types/tools.py
- tests/strands/agent/test_agent.py
- tests/strands/event_loop/test_event_loop.py
- tests/strands/handlers/test_tool_handler.py
- tests/strands/models/test_bedrock.py
This refactors how kwargs are handled within the Agent class. Instead of allowing certain override parameters to be passed in via kwargs, we instead rely on the agent's attributes. After invoking an agent, or using a direct tool call, the kwargs are passed around as a dict instead of being spread.
N/A
TODO if there are any docs changes needed
----
> refactor: remove kwargs spread after agent call

- src/strands/event_loop/event_loop.py
- src/strands/telemetry/tracer.py
- tests/strands/telemetry/test_tracer.py
Update semantic conventions for Gen-AI spans
refs:
1. https://opentelemetry.io/docs/specs/semconv/registry/attributes/gen-ai/
2. https://opentelemetry.io/docs/specs/semconv/gen-ai/gen-ai-agent-spans/#invoke-agent-span
3. https://opentelemetry.io/docs/specs/semconv/gen-ai/gen-ai-spans/#execute-tool-span
4. https://opentelemetry.io/docs/specs/semconv/gen-ai/gen-ai-events/#event-gen_aitoolmessage
https://github.com/strands-agents/private-sdk-python-staging/issues/77
Will update the doc
chore: semantic conventions
- [] I have updated the documentation accordingly
- [] I have added an appropriate …
> chore: updated semantic conventions on Generative AI spans

- src/strands/agent/agent.py
- src/strands/telemetry/tracer.py
- tests/strands/agent/test_agent.py
Allow customer to set agent name
https://github.com/strands-agents/sdk-python/issues/277
No need to update
New feature with small changes
----
> chore: allow custom agent name

- src/strands/multiagent/a2a/executor.py
- src/strands/multiagent/a2a/server.py
- tests/multiagent/a2a/conftest.py
- tests/multiagent/a2a/test_executor.py
- tests/multiagent/a2a/test_server.py
- Implemented streaming support for `A2AServer`.
- Clients can now use the `A2AServer` in streaming and non-streaming mode. The underlying executor supports both modes of execution and uses the `stream_async` and `invoke_async` functions accordingly.
- The `A2AServer` also supports [Tasks](https://a2aproject.github.io/A2A/v0.2.5/topics/streaming-and-async/) where the request status is incrementally updated via the `Task` interface. This works gracefully in either streaming or synchronous mode. In streaming mode updates are sent via `SSE`, in sync mode an `A2A` response payload is returned with the task once it is complete.
- https://github.com/strands-agents/private-sdk-python-staging/issues/97
- https://github.com/strands-agents/private-sdk-python-staging/issues/95
- N/A coming soon
New …
> a2a streaming

- src/strands/multiagent/a2a/server.py
Updated `A2AServer` __init__ docstrings to reflect changes to class name and parameters
- Changed 'A2A-compatible agent' to 'A2A-compatible server'
- Removed 'name' and 'description'
----
> docs(multiagent): Update A2AServer docstrings

- src/strands/event_loop/event_loop.py
- src/strands/experimental/hooks/__init__.py
- src/strands/experimental/hooks/events.py
- src/strands/experimental/hooks/registry.py
- tests/fixtures/mock_hook_provider.py
- tests/strands/agent/test_agent_hooks.py
- tests/strands/event_loop/test_event_loop.py
- tests/strands/experimental/hooks/test_events.py
This PR adds two new hook events that fire before and after tool execution, allowing hooks to inspect and modify tool calls and their results. The hook system has been enhanced to support selective property updates on event objects.
**New Hook Events**
- `BeforeToolInvocation` : Fires before a tool is executed, allowing modification of the selected tool and parameters
- `AfterToolInvocation`: Fires after tool execution completes, allowing modification of the result
**Enhanced Hook Registry**
The base `HookEvent` class now includes a property write protection system. Event classes can override `_can_write()` to specify which properties hooks are allowed to modify. This prevents accidental modification of read-only properties while enabling controlled updates where needed.
**Tool …
> feat: Add hooks for before/after tool calls + allow hooks to update values

- pyproject.toml
Google recently updated the A2A SDK with DB support and this is a non-optional dependency. https://github.com/a2aproject/a2a-python/pull/259. 
When using A2A without this dependency the following error message is show: 
```
E   ImportError: DatabaseTaskStore requires SQLAlchemy and a database driver. Install with one of: 'pip install a2a-sdk[postgresql]', 'pip install a2a-sdk[mysql]', 'pip install a2a-sdk[sqlite]', or 'pip install a2a-sdk[sql]'
```
Dependency bump
----
> deps(a2a): upgrade a2a with db support

- tests_integ/models/test_model_mistral.py
We can't reuse the same agent instance when running in parallel and these were failing locally.  Now they are not.
N/A
N/A
Bug fix
----
> Fix: Update mistral tests to avoid shared agents

- tests_integ/models/conformance.py
- tests_integ/models/providers.py
Add code infrastructure to be able to run a set of tests against all providers. 
I needed to run some code against all providers and rather than continuing to copy/paste it locally, set us up for running a test or set of tests against all providers.  The only test added so far is one that validates that models can be constructed but it sets us up for success later.
#313.
N/A
New feature
----
> Add basis for conformance-based tests

- src/strands/event_loop/event_loop.py
- src/strands/experimental/hooks/__init__.py
- src/strands/experimental/hooks/events.py
- src/strands/experimental/hooks/rules.md
- tests/strands/agent/test_agent_hooks.py
- tests/strands/event_loop/test_event_loop.py
This PR introduces new hook events that allow subscribers to monitor and interact with model invocations during agent execution.  Each call to the model from the event loop will fire these events, even if we're going to retry the request.  In the future I think we could expand the `AfterModelInvocationEvent` to reimplemenet retries and allow customers to specify how the request is retried, but that will require further design.
**Changes:**
- Added `BeforeModelInvocationEvent` and `AfterModelInvocationEvent` to the experimental hooks system
- The `AfterModelInvocationEvent` includes model response data and stop reason information
- Initially I had tool specifications included on the events and modifable in the BeforeEvent.  I decided against this after initial implementation to refine the …
> Add Model Invocation Hooks

- src/strands/tools/mcp/mcp_agent_tool.py
- src/strands/tools/mcp/mcp_client.py
- tests/strands/tools/mcp/test_mcp_agent_tool.py
- tests/strands/tools/mcp/test_mcp_client.py
This is a followup to #391 to provide an `call_tool_async` function for the MCP client.
New feature
Sample script:
```python
import logging
from mcp import StdioServerParameters, stdio_client
from strands import Agent
from strands.models.openai import OpenAIModel
from strands.tools.mcp import MCPClient
logging.basicConfig(level=logging.DEBUG)
API_KEY="<insert api key>"
stdio_mcp_client = MCPClient(
lambda: stdio_client(StdioServerParameters(command="uvx", args=["awslabs.aws-documentation-mcp-server@latest"]))
)
with stdio_mcp_client:
tools = stdio_mcp_client.list_tools_sync()
model = OpenAIModel(
{
"api_key": API_KEY,
}, …
```
> feat(async): mcp async call tool

- src/strands/agent/agent.py
- src/strands/experimental/hooks/__init__.py
- src/strands/experimental/hooks/events.py
- tests/strands/agent/test_agent_hooks.py
- tests/strands/experimental/hooks/test_events.py
To conform to our rules that Indicate that Start/After is the preferred terminology + changing to invocation which should be more clear.
#231
Other (please describe): Refactor
----
> Rename StartRequestEvent & EndRequestEvent events

- src/strands/agent/agent.py
- src/strands/tools/registry.py
- tests_integ/test_hot_tool_reload_decorator.py
BREAKING CHANGE: load_tools_from_directory will now default to False
Description
This PR updates the Agent property load_tools_from_directory to default to False instead of True.
This is being done to prevent a threat where an Agent has file write access which is then prompt injected to generate a tool which gets used by the Agent on subsequent runs. Auto loading of tools is a useful feature, but one which introduces new risks which may not be obvious to customers. Instead, we will default to False where customers will need to diliberately set the boolean to use the feature.
Related Issues
https://github.com/strands-agents/agent-builder/pull/38
Documentation PR
N/A
Type of Change
Testing
How have you tested the change?  Verify that the changes do not break functionality or …
> chore!: set Agent property load_tools_from_directory to default to False

- src/strands/multiagent/a2a/executor.py
- src/strands/multiagent/a2a/server.py
Changes
1. allow host and port to be overridden in serve function
2. remove excessive logging in executor
----
> refactor(a2a): configurable host and port and remove excessive logging

- src/strands/multiagent/base.py
- src/strands/multiagent/graph.py
- tests/strands/multiagent/test_graph.py
- tests_integ/test_multiagent_graph.py
Graph - support multi-modal inputs
#214 
TODO
New feature
----
> feat(multiagent): Graph - support multi-modal inputs

- src/strands/tools/mcp/mcp_client.py
- src/strands/types/__init__.py
- src/strands/types/collections.py
- tests/strands/tools/mcp/test_mcp_client.py
This PR adds pagination support to the list_tools_sync method in the MCP client by introducing a new PaginatedList generic collection type. Previously, list_tools_sync returned a simple list without any pagination capabilities, which could be problematic when dealing with MCP servers that have large numbers of tools. FastMCP always returns all tools, so this is likely why customers have not encountered this before.
Key Changes:
* Created src/strands/types/collections.py with a new PaginatedList class that extends list while adding a pagination_token attribute
* Updated list_tools_sync method signature to accept an optional pagination_token parameter and return PaginatedList[MCPAgentTool] instead of List[MCPAgentTool]
* Added proper handling of the MCP server's nextCursor response to …
> feat!: add pagination to mcp_client list_tools_sync

- src/strands/telemetry/tracer.py
- tests/strands/telemetry/test_tracer.py
Align the span names to be underscored
N/A
N/A
small update
----
> chore: update span names

- pyproject.toml
- src/strands/tools/structured_output.py
- tests/strands/tools/test_structured_output.py
Previously lists of items that were optional were not correctly expanding $refs. Derived classes also weren't having their $refs expanded as the subclass already had a "properties" object which bypassed $ref expansion
Fixes #337 
Created a follow-up issue to remove this ref expansion altogether: #438
N/A
Bug fix
----
> Expand additional $refs for structured_output

- src/strands/session/file_session_manager.py
- src/strands/session/repository_session_manager.py
- src/strands/session/s3_session_manager.py
- src/strands/session/session_repository.py
- src/strands/types/session.py
- tests/strands/session/test_file_session_manager.py
- tests/strands/session/test_repository_session_manager.py
- tests/strands/session/test_s3_session_manager.py
- tests/strands/types/test_session.py
- Fix session manager to track the last message for every agent
- Change how messages are stored. use index instead of created_at time when naming the file
N/A
N/A
Bug fix
----
> fix: session manager tracks all agent last message

- src/strands/agent/agent.py
- src/strands/agent/conversation_manager/conversation_manager.py
- src/strands/agent/conversation_manager/sliding_window_conversation_manager.py
- src/strands/agent/conversation_manager/summarizing_conversation_manager.py
- src/strands/session/file_session_manager.py
- src/strands/session/repository_session_manager.py
- src/strands/session/s3_session_manager.py
- src/strands/session/session_manager.py
- src/strands/types/session.py
- tests/fixtures/mock_session_repository.py
- tests/strands/agent/test_agent.py
- tests/strands/agent/test_conversation_manager.py
- tests/strands/agent/test_summarizing_conversation_manager.py
- tests/strands/session/test_file_session_manager.py
- tests/strands/session/test_repository_session_manager.py
- tests/strands/session/test_s3_session_manager.py
- tests/strands/types/test_session.py
- tests_integ/test_session.py
Store conversation manager state as a part of the session
N/A
https://github.com/strands-agents/docs/pull/146
New feature
----
> feat: Store conversation manager in session

- README.md
Update logo so that in dark mode the other strand is available
*Before*
*After*
*After light mode*
----
> Switch readme to use light logo for better display in github dark mode

- src/strands/agent/agent.py
- tests/strands/agent/test_agent.py
This PR fixes a critical issue where passing non-serializable objects as tool parameters would cause JSON serialization errors during tool call recording, leading to crashes when agents tried to record their tool usage.
When agents passed complex objects like Agent instances, custom classes, functions, or other non-JSON-serializable objects as tool parameters, the `_record_tool_execution()` method would fail with cryptic JSON serialization errors, breaking the entire tool execution flow.
- **Smart Parameter Filtering**: Added logic to test each parameter with `json.dumps()` before recording
- **Graceful Degradation**: Replace non-serializable objects with descriptive strings like `<non-serializable: TypeName>`
- **Maintain Functionality**: Tool execution continues normally while providing …
> fix(agent): prevent JSON serialization errors with non-serializable direct tool parameters

- src/strands/agent/agent.py
- src/strands/event_loop/event_loop.py
- src/strands/telemetry/tracer.py
Fix tracing issue when using agent as tool in an agent
I've tested on langfuse and CW, need to add unit tests later on.
To-do: Add unit tests
https://github.com/strands-agents/sdk-python/issues/489
N/A
Bug fix
----
> fix(telemetry): group traces when using agent as tool in an agent

- pyproject.toml
- src/strands/multiagent/a2a/server.py
Min version bump of A2A to address breaking changes which modify parameters from camelCase -> snake_case.
Found originally by @zastrowm in https://github.com/strands-agents/sdk-python/pull/508
Bug fix
New feature
----
> deps(a2a): address interface changes and bump min version

- .github/workflows/pr-and-push.yml
These were necessary when we had conditional running but we switched to needing to approve all workflows for non-maintainers, so we no longer need these.
Bug fix
----
> Don't re-run workflows on un/approvals

- src/strands/multiagent/a2a/server.py
- src/strands/session/repository_session_manager.py
- tests/strands/multiagent/a2a/test_server.py
Description
This PR adds native support for configurable public URLs and automatic path-based mounting to the `A2AServer` class, enabling seamless deployment in containerized environments and behind load balancers with path-based routing.
**1. New `http_url` Parameter**
- Added `http_url: str | None = None` parameter to `A2AServer` constructor
- When provided, overrides the auto-generated URL from `host:port` for public agent card URLs
- Maintains separate concerns: `host`/`port` for internal binding, `http_url` for external access
**2. Automatic Path-Based Mounting** 
- When `http_url` contains a path component, the server automatically mounts the A2A application at that path
- Uses framework-native Starlette/FastAPI mounting capabilities (no middleware required)
- Handles URL parsing …
> feat(a2a): support mounts for containerized deployments

- src/strands/telemetry/tracer.py
- src/strands/tools/executor.py
Include agent trace into tool span when using agent as tool
Trace structure before the change: [link](https://us.cloud.langfuse.com/project/cmbb4s57d01xiad07eex8qvrl/traces/275246a35d032eb2e87465f35917fa64?timestamp=2025-07-23T18:21:33.462Z&display=details)
Trace after the change: [link](https://us.cloud.langfuse.com/project/cmbb4s57d01xiad07eex8qvrl/traces/0bbf6160feacff2949f0e18caebbf9b4?timestamp=2025-07-23T18:26:38.461Z&display=details)
Will attach it
N/A
Bug fix
----
> fix: include agent trace into tool for agent as tools

- src/strands/models/sagemaker.py
Remove debug print statement that was leftover during development. 
Bug fix
New feature
----
> fix: Remove leftover print statement from sagemaker model provider

- src/strands/models/anthropic.py
Using a string as suggested by the type annotation causes the Anthropic API call to fail:
```
anthropic.BadRequestError: Error code: 400 - {'type': 'error', 'error': {'type': 'invalid_request_error', 'message': 'max_tokens: Input should be a valid integer'}}
```
Just a quick type change.
Documentation actually looks right, just the type annotation is incorrect.
Bug fix
----
> Change max_tokens type to int to match Anthropic API

- src/strands/multiagent/a2a/server.py
This change allows customers to configure the following attributes of the A2A request handler:
- `task_store`: Custom task storage implementation (defaults to `InMemoryTaskStore`)
- `queue_manager`: Custom message queue management (optional)
- `push_config_store`: Custom push notification configuration storage (optional)  
- `push_sender`: Custom push notification sender implementation (optional)
These parameters are now optional constructor arguments in `A2AServer`, providing extensibility points for custom implementations while maintaining backward compatibility.
**Backward Compatibility:** There are no functional changes to existing A2AServer usage - all new parameters have sensible defaults.
```python
server = A2AServer(
strands_agent=my_agent,
host="localhost", 
port=8000
)
``` …
> feat(a2a): configurable request handler

- src/strands/tools/mcp/mcp_client.py
This PR Introduces a server startup timeout configuration option in MCPClient to enable long-running startups, such as uv which can install dependencies at runtime.
Also some minor auto-formatting changes added by hatch.
NA
NA
New feature
----
> feat: Add configuration option to MCP Client for server init timeout

- src/strands/agent/agent.py
- tests/strands/agent/test_agent.py
Add a span for structured_output, which contains the messages and the response.
N/A
N/A
New feature
----
> feat: add structured_output_span

- src/strands/agent/agent.py
- tests/strands/agent/test_agent.py
This PR fixes the order of system_prompt and input_messages in `structured_output_span` .
The system_prompt should added before input_message, and align with the order of what sent to model_provider, inside of `model.structured_output`.
https://github.com/strands-agents/sdk-python/issues/692
N/A
Bug fix
----
> fix: add system_prompt to structured_output_span before adding input_messages

- src/strands/_identifier.py
- src/strands/session/file_session_manager.py
- src/strands/session/s3_session_manager.py
- tests/strands/session/test_file_session_manager.py
- tests/strands/session/test_s3_session_manager.py
Fixing a path_traversal security issue in `FileSessionManager` and `S3SessionManager` specifically in our `_get_message_path()` method. Currently we don't validate the `message_id` but we do validate the other id's such as `session_id` and `agent_id`
This PR fixes the issue by raising an exception if the message_id contains separators.
Bug fix
New feature
----
> fix: prevent path traversal for message_id in file_session_manager

- CONTRIBUTING.md
- src/strands/agent/agent.py
- src/strands/session/file_session_manager.py
- src/strands/session/s3_session_manager.py
- tests/strands/agent/test_agent.py
- tests/strands/session/test_file_session_manager.py
- tests/strands/session/test_s3_session_manager.py
Add type alias for the input type for invoking an agent
N/A
Other - Minor fix
----
> fix: Add AgentInput TypeAlias

- src/strands/agent/agent.py
- src/strands/event_loop/event_loop.py
- src/strands/tools/executors/_executor.py
- src/strands/tools/executors/concurrent.py
- src/strands/tools/executors/sequential.py
- src/strands/types/_events.py
- tests/strands/agent/test_agent.py
- tests/strands/event_loop/test_event_loop.py
- tests/strands/event_loop/test_streaming.py
- tests/strands/tools/executors/test_concurrent.py
- tests/strands/tools/executors/test_executor.py
- tests/strands/tools/executors/test_sequential.py
This is step step 2/N of implementing typed-events:
Related PRs:
1. #745
Migrate "callback" nested properties and explicitly passing invocation_state to behaviors on the TypedEvent:
- `TypedEvent.is_callback_event` for determining if an event should be yielded and or invoked in the callback
- `TypedEvent.prepare` for taking in invocation_state (and optionally merging it in)
- This is only for backwards compatibility; certain events need to be merged in with invocation_state, and now we can move away from passing `invocation_state` throughout the system
Customers still only get dictionaries, as we decided that this will remain an implementation detail for the time being, but this makes the events typed all the way up until *just* before we yield events back to the caller
As part of this …
> feat: Use TypedEvent inheritance for callback behavior

- src/strands/models/bedrock.py
- tests/strands/models/test_bedrock.py
fix stop reason in bedrock model.
This issue is raised from side team, Bedrock returns stop_reason : "end_turn" in some tool use cases, which caused Strands SDK can't execute tool call in event loop. So we special case this for now, waiting for bedrock team fixing the issue.
Test with code in this link: https://github.com/strands-agents/sdk-python/issues/644
Bug fix
New feature
- [x ] I ran `hatch run prepare`
- [ x] I have read the CONTRIBUTING document
- [x ] I have added any necessary tests that prove my fix is effective or my feature works
- [x ] I have …
> fix: fix stop reason for bedrock model when stop_reason

- src/strands/tools/registry.py
- tests/strands/tools/test_registry.py
fix duplicate tool names, throw Value Erro while tools have same name, except tool.support_hot_reload is true.
https://github.com/strands-agents/sdk-python/issues/715
Bug fix
New feature
test with aws mcp server.
```
stdio_mcp_client = MCPClient(lambda: stdio_client(
StdioServerParameters(
command="uvx",
args=["awslabs.aws-documentation-mcp-server@latest"]
)
))
@tool
def read_documentation():
return ""
test_tool = None
with stdio_mcp_client:
for tool in stdio_mcp_client.list_tools_sync():
if tool.tool_name == "read_documentation":
test_tool = tool
agent = Agent(tools=[read_documentation,test_tool])
print(agent.tool_names)
```
```
[08/29/25 15:32:47] INFO     Processing request of type ListToolsRequest …
```
> fix: fix loading tools with same tool name

- src/strands/tools/loader.py
- src/strands/tools/mcp/mcp_client.py
- src/strands/tools/registry.py
- src/strands/tools/tools.py
- tests/strands/tools/test_loader.py
Previously, passing a file path that contained multiple `@tool` decorated functions resulted in only one tool being loaded/registered. This made file-based tool loading inconsistent with directory/module scanning (which returns all decorated tools). This PR fixes that: the file-path loader now collects all decorated function tools and returns them; the registry is updated to register each tool individually. Unit tests and linters were updated and run locally.
- Collect all `DecoratedFunctionTool` objects when loading a `.py` file and return a `list` when multiple exist.
- Normalize loader results and register each `AgentTool` separately in the registry.
- Add `normalize_loaded_tools` helper to `src/strands/tools/tools.py`.
- Add unit test …
> fix(tools/loader): load and register all decorated @tool functions from file path

- src/strands/models/llamacpp.py
fix(llama.cpp) - add ToolChoice and validation of model config values
N/A
N/A
Bug fix
----
> fix(llama.cpp) - add ToolChoice and validation of model config values

- src/strands/models/litellm.py
- tests/strands/models/test_litellm.py
- tests_integ/models/test_model_litellm.py
Our integ test has been failing for some time.  I am not certain what changed but my expectation is it is the quality of the underlying model. To fix this I made the pydantic model more descriptive. I am comfortable with this rather than diving deeper on a fix because the change did not modify our test logic at all. Rather, this simply provides more context to the llm.
Bug fix
----
> fix: litellm structured_output test with more descriptive model

- README.md
docs(README): fix links and imports
N/A
N/A
Bug fix
----
> docs(README): fix links and imports

- pyproject.toml
`hatch run prepare` should prep all the files to ensure it's ready for a PR, so switch it to format files instead of testing the format. Otherwise it just quits with output of the files that need to be formatted
N/A
N/A
Bug fix
----
> fix: Update prepare to use format instead of test-format

- .github/workflows/auto-close.yml
Add permissions block with minimal required permissions
🤖 Assisted by Amazon Q Developer
N/A
N/A
Bug fix
----
> fix: add explicit permissions to auto-close workflow

- src/strands/tools/mcp/mcp_client.py
- src/strands/tools/mcp/mcp_instrumentation.py
- tests/strands/tools/mcp/test_mcp_client.py
- tests/strands/tools/mcp/test_mcp_instrumentation.py
- tests_integ/test_mcp_client.py
- Add module-level flag _instrumentation_applied to track patch state
- Return early from mcp_instrumentation() if already applied
- Prevents wrapper accumulation that causes RecursionError with multiple MCPClient instances
- Add integration tests for multiple client creation and thread safety
🤖 Assisted by Amazon Q Developer
Fixes #869 
N/A
Bug fix
----
> fix: make mcp_instrumentation idempotent to prevent recursion errors

- .github/workflows/test-lint.yml
- .pre-commit-config.yaml
There is a bug in click which is impacting `hatch run`: https://github.com/pypa/hatch/issues/2052
This pr updates our automation to use `hatch fmt` instead of `hatch run` to help avoid this issue while its fixed.
https://github.com/pypa/hatch/issues/2052
N/A
Bug fix
----
> fix: Fix github workflow to use fmt instead of hatch run

- src/strands/models/anthropic.py
- src/strands/models/bedrock.py
- src/strands/models/litellm.py
- src/strands/models/llamaapi.py
- src/strands/models/llamacpp.py
- src/strands/models/mistral.py
- src/strands/models/model.py
- src/strands/models/ollama.py
- src/strands/models/openai.py
- src/strands/models/sagemaker.py
- src/strands/models/writer.py
- tests/strands/models/test_model.py
The release of v1.8.0 introduced [tool_choice to the Model interface to better support structured_output](https://github.com/strands-agents/sdk-python/pull/720). This was accidentally added as a positional argument instead of a keyword argument. This is breaking for custom implementations of the Model interface.
The fix here is to switch to an optional keyword arg.
Bug fix
----
> fix(models): make tool_choice an optional keyword arg instead positional

- src/strands/event_loop/streaming.py
- src/strands/models/bedrock.py
- src/strands/tools/mcp/mcp_agent_tool.py
- src/strands/types/tools.py
- tests/strands/models/test_bedrock.py
- tests/strands/tools/mcp/test_mcp_agent_tool.py
- tests_integ/mcp/__init__.py
- tests_integ/mcp/echo_server.py
- tests_integ/mcp/test_mcp_client.py
- tests_integ/mcp/test_mcp_client_structured_content_with_hooks.py
- tests_integ/mcp/test_mcp_output_schema.py
This PR adds support for MCP output schema tool specifications as defined in the MCP specification (https://modelcontextprotocol.io/specification/2025-06-18/server/tools#data-types). This allows tools to define their expected output structure through outputSchema, which is particularly valuable for LLM agents to better understand tool capabilities and responses.
Note, the LLM is not automatically shown the outputSchema. In the future certain models may accept but. But for now, it is a device that users can leverage internally. For example if someone wanted to create their own dynamic tool loader they could use the outputSchema as a message.
As part of this we needed to make sure the BedrockModel explicitly manages its supported fields (including handling outputSchema appropriately), while …
> feat: add optional outputSchema support for tool specifications

- src/strands/models/openai.py
- tests/strands/models/test_openai.py
- tests_integ/models/test_model_openai.py
This PR fixes proper exception handling for OpenAI model provider to correctly distinguish between context window overflow and rate limiting errors. Previously, the OpenAI model provider did not handle these errors, causing them to bubble up as raw OpenAI SDK exceptions instead of being converted to the SDK's standardized exception types.
1. **Added proper exception handling** for both `stream()` and `structured_output()` methods
2. **Context window errors** (HTTP 400, `context_length_exceeded`) → `ContextWindowOverflowException`
3. **Rate limit errors** (HTTP 429, `rate_limit_exceeded`) → `ModelThrottledException`
4. **Comprehensive test coverage** for all error scenarios
5. **Updated docstrings** to document the new exception behavior
OpenAI has two separate token limits that cause …
> Improve OpenAI error handling 

- src/strands/models/gemini.py
This PR fixes a critical issue where the Gemini model provider would fail with `RuntimeError: Event loop is closed` when used in multi-turn conversations. The problem occurred when multiple synchronous agent calls were made sequentially, each creating a new event loop via `asyncio.run()`.
The original implementation stored a single `genai.Client` instance during initialization, which would bind its underlying HTTP session (aiohttp) to the first event loop. When subsequent calls created new event loops, the old HTTP session would attempt to use the closed event loop, causing the runtime error.
Changed the Gemini model to create a fresh client for each async operation instead of reusing a single instance:
**Before:**
```python
def __init__(self, ...):
self.client = …
```
> fix(gemini): Fix event loop closed error from Gemini asyncio

- src/strands/tools/mcp/mcp_client.py
- tests_integ/mcp/test_mcp_client.py
Fixed the timeout issue with the mcp client when the http server times out before the tool finishes
I was able to replicate this bug by creating an mcp server with a tool that waits ~5 seconds, and then configuring the mcp client to time out before that:
MCP Server
```
from fastmcp import FastMCP
import time
app = FastMCP()
@app.tool("say")
def say(input: str) -> str:
"""Says something."""
time.sleep(5)
return f"{input}!"
if __name__ == "__main__":
app.run(transport="http", host="localhost", port=8080)
```
Test code:
```
from strands.tools.mcp import MCPClient
from mcp.client.streamable_http import streamablehttp_client
client = MCPClient(lambda: streamablehttp_client(
sse_read_timeout=2,
url="http://localhost:8080/mcp"))
with client as mcp:
mcp.call_tool_sync(tool_use_id="123", …
```
> fix: Fix mcp timeout issue

- src/strands/tools/tools.py
- tests/strands/tools/test_registry.py
- tests/strands/tools/test_tools.py
I've noticed that in our module based tools, we're not setting the `supports_hot_reload` property, which leads to not hot-reload those tools.
- Add supports_hot_reload property that returns True for function-based tools
- This enables proper hot reload support for TOOL_SPEC + function() pattern tools
- Aligns with the conditional check in PR #772 for tool reloading logic
----
> feat: add supports_hot_reload property to PythonAgentTool

- src/strands/telemetry/tracer.py
- tests/strands/telemetry/test_tracer.py
Remove double serialization when adding events into the span.
https://github.com/strands-agents/sdk-python/pull/952
https://github.com/strands-agents/sdk-python/issues/877
TBD
Fix
----
> fix(telemetry): removed double serialization for events

- src/strands/models/litellm.py
- tests/strands/models/test_litellm.py
Previously, when LiteLLM raised a context window related error , it wasn’t mapped to our standard ContextWindowOverflowException. This update fixes that by detecting these errors and raising ContextWindowOverflowException so that agents can handle input more reliably.
- Updated src/strands/models/litellm.py to catch LiteLLM client exceptions and raise ContextWindowOverflowException for context-window overflow messages
- Adjusted structured_output logic to ensure mapping occurs before unsupported model checks when relevant.
- Updated the test file tests/strands/models/test_litellm.py to patch supports_response_schema where needed, ensuring the test properly covers the exception mapping path.
Fixes #974 
N/A
Bug fix
How have you tested the change?  Verify that the changes do not break …
> fix(litellm): map LiteLLM context window errors to ContextWindowOverflowException
